export const metadata = {
	title: 'Product page',
	description: 'Generated by create next app',
};

const ProductPage = ({ params, searchParams }) => {
	return <div>ProductPage {params.id}</div>;
};

export default ProductPage;
